version: '3.9'

services: 
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5466:5432"
    # volumes:
    #   - ./data/sql/:/var/lib/postgresql/data